# test_tenant.py

import asyncio
import os
import uuid
from datetime import datetime

from dotenv import load_dotenv

from sqlalchemy import (
    String,
    Text,
    Boolean,
    DateTime,
    select,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.ext.asyncio import (
    create_async_engine,
    async_sessionmaker,
)
from sqlalchemy.orm import (
    DeclarativeBase,
    Mapped,
    mapped_column,
)


# --------------------------------------------------
# Load environment variables
# --------------------------------------------------

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")

if not DATABASE_URL:
    raise RuntimeError("DATABASE_URL not found in environment variables")


# --------------------------------------------------
# Base
# --------------------------------------------------

class Base(DeclarativeBase):
    pass


# --------------------------------------------------
# Tenant Model
# --------------------------------------------------

class Tenant(Base):
    __tablename__ = "tenants"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
    )

    company_name: Mapped[str] = mapped_column(
        String(250),
        nullable=False,
    )

    slug: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
    )

    currency: Mapped[str | None] = mapped_column(
        String(3),
        nullable=True,
    )

    timezone: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
    )

    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
    )

    created_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
    )

    updated_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
    )

    ntn_cnic: Mapped[str | None] = mapped_column(
        String(20),
    )

    province: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
    )

    city: Mapped[str | None] = mapped_column(
        String(100),
    )

    address: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    sandbox_environment_token: Mapped[str | None] = mapped_column(
        Text,
    )

    production_environment_token: Mapped[str | None] = mapped_column(
        Text,
    )


# --------------------------------------------------
# Database
# --------------------------------------------------

engine = create_async_engine(
    DATABASE_URL,
    echo=True,  # shows SQL generated by SQLAlchemy
)

SessionLocal = async_sessionmaker(
    engine,
    expire_on_commit=False,
)


# --------------------------------------------------
# Test
# --------------------------------------------------

async def main():

    async with SessionLocal() as session:

        result = await session.execute(
            select(Tenant)
        )

        tenants = result.scalars().all()

        print("\n\n========== TENANTS ==========\n")

        for tenant in tenants:

            print("ID:", tenant.id)
            print("Company:", tenant.company_name)

            print("Province:", repr(tenant.province))
            print("City:", repr(tenant.city))
            print("Address:", repr(tenant.address))

            print("NTN/CNIC:", repr(tenant.ntn_cnic))

            print("-" * 60)

    await engine.dispose()


if __name__ == "__main__":
    asyncio.run(main())